name: community_calendar
description: Discover Stuff You Care About

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  dio: ^4.0.6
  material_design_icons_flutter: ^5.0.6996
  font_awesome_flutter: ^10.1.0
  url_strategy: ^0.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  velocity_x: ^3.5.1
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

